[package]
name = "telelog-proto"
description = "gRPC wire types for Telelogs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
prost.workspace = true
prost-types.workspace = true
telelog-core.workspace = true
tonic.workspace = true
tonic-prost.workspace = true

[build-dependencies]
protoc-bin-vendored = "3"
tonic-prost-build.workspace = true
