[package]
name = "telelog-app"
description = "Telelogs desktop app"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "telelogs"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }
clap.workspace = true
futures.workspace = true
rust-embed = "8"
serde_json = { version = "1", features = ["preserve_order"] }
gpui-kit = "0.7"
telelog-core.workspace = true
telelog-proto.workspace = true
tokio.workspace = true
tonic.workspace = true
