[package]
name = "telelog-server"
description = "Telelogs server: collects logs and streams them to the desktop app"
version.workspace = true
edition.workspace = true
license = "AGPL-3.0-only"

[dependencies]
anyhow.workspace = true
clap.workspace = true
futures.workspace = true
telelog-core.workspace = true
telelog-proto.workspace = true
telelog-sources.workspace = true
tokio.workspace = true
tonic.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
