[package]
name = "telelog-sources"
description = "Log sources (Docker, Kubernetes, VMs) for Telelogs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
bollard.workspace = true
futures.workspace = true
humantime = "2"
telelog-core.workspace = true
tracing.workspace = true
